# Generated by Django 4.1.4 on 2022-12-23 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="categories",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category_name", models.CharField(max_length=100)),
                ("date", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="category_list",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brand", models.TextField()),
                ("datetime", models.DateTimeField()),
                ("originalprice", models.CharField(max_length=100)),
                ("price", models.CharField(max_length=100)),
                ("discount", models.CharField(max_length=100)),
                ("rating", models.CharField(max_length=10)),
                (
                    "cat_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="E_commerce_app.categories",
                    ),
                ),
            ],
        ),
    ]
