# Generated by Django 4.1.4 on 2022-12-24 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("E_commerce_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categories",
            name="category_name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="category_list",
            name="originalprice",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="category_list",
            name="price",
            field=models.FloatField(default=0),
        ),
    ]
